[theme]
primaryColor = "#00ADB5"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
